version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: dbsystemks
      POSTGRES_DB: mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - unitycicle

  app:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app/back
      - /usr/src/app/back/node_modules
    depends_on:
      - postgres
    networks:
      - unitycicle
    entrypoint:
      [
        'bash',
        '-c',
        'while !</dev/tcp/postgres/5432; do sleep 1; done; npm run start',
      ]

volumes:
  postgres:

networks:
  unitycicle:
